apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-order
  template:
    metadata:
      labels:
        app: web-order
    spec:
      containers:
      - name: web-order-container
        image: web-order-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-tracking-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-tracking
  template:
    metadata:
      labels:
        app: order-tracking
    spec:
      containers:
      - name: order-tracking-container
        image: order-tracking-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-confirmation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-confirmation
  template:
    metadata:
      labels:
        app: order-confirmation
    spec:
      containers:
      - name: order-confirmation-container
        image: order-confirmation-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-confirmation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-confirmation
  template:
    metadata:
      labels:
        app: delivery-confirmation
    spec:
      containers:
      - name: delivery-confirmation-container
        image: delivery-confirmation-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-order-accept-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-order-accept
  template:
    metadata:
      labels:
        app: web-order-accept
    spec:
      containers:
      - name: web-order-accept-container
        image: web-order-accept-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083