apiVersion: v1
kind: Service
metadata:
  name: web-order-service
spec:
  type: NodePort
  selector:
    app: web-order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: order-tracking-service
spec:
  selector:
    app: order-tracking
  ports:
  - port: 8080        # The port that this service will expose
    targetPort: 8080  # The port on the logging-container
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: order-confirmation-service
spec:
  selector:
    app: order-confirmation
  ports:
  - port: 8081      # The port that this service will expose
    targetPort: 8081  # The port on the logging-container
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-confirmation-service
spec:
  selector:
    app: delivery-confirmation
  ports:
  - port: 8082        # The port that this service will expose
    targetPort: 8082  # The port on the logging-container
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-order-accept-service
spec:
  selector:
    app: web-order-accept
  ports:
  - port: 8083       # The port that this service will expose
    targetPort: 8083  # The port on the logging-container
    protocol: TCP
